[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "mssqlclient-ng"
version = "0.1.0"
description = "Interract with Microsoft SQL Server (MS SQL | MSSQL) servers and their linked instances, without the need for complex T-SQL queries."
authors = [
    {name = "n3rada",email = "72791564+n3rada@users.noreply.github.com"}
]
license = {text = "GPL-3.0-or-later"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "impacket[tds] (>=0.13.0,<0.14.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "prompt-toolkit (>=3.0.52,<4.0.0)"
]


[project.urls]
repository  = "https://github.com/n3rada/mssqlclient-ng"

[project.scripts]
mssqlclient-ng = 'mssqlclient_ng.cli:main'
